name: pymc_tutorial

channels:
 - conda-forge
 
dependencies:
- python=3.5
- ipython
- jupyter
- notebook
- seaborn 
- patsy 
- pandas
- pip:
    - pymc3
    - git+https://github.com/Theano/Theano.git#egg=theano
