name: pymc

channels:
 - conda-forge
 
dependencies:
- python=3.5
- ipython
- jupyter
- notebook
- seaborn 
- patsy 
- pandas
- pip:
    - git+https://github.com/Theano/Theano.git#egg=theano
    - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3
